#+BEGIN_HTML
---
title: My Resume.
excerpt: Some infomation of my work experience.
featured: /assets/images/pic00.jpg
categories:
    - personal
tags:
    - profile
layout: post
---
#+END_HTML
#+STARTUP: showall
#+STARTUP: hidestars
* Experience and Resume
    + profile
      + Education
      + Work Experiences.

讯技光电（上海）有限公司主要业务是光学仿真软件，包括美国的FRED， Macleod，德国的 VirtualLab 等。

我的职责包括：
1) 软件接口的二次开发。
2) 承接光学设计专案。
3) 软件售后的培训课程。
4) 客户问题技术支持，与原厂沟通。接受国外专家的培训。
4) 软件相关书籍翻译（主要英译汉）。

在职期间，
1) 搭建并维护内网服务器一部，使用 redhat 与 samba 服务，方便管理公司资料。
2) 承接光学设计仿真专案若干，包括光纤与成像系统仿真等。
3) 翻译国外镀膜设计专著一本（约27万字, 公式排版校对等部分工作有同事和一名实习生帮助）。
http://www.infotek.com.cn/html/26/20150810574.html
校正更新书籍一本（FRED光学工程仿真，约500页，增加4章）。
http://infotek.com.cn/html/26/20111013289.html
4) 与合作公司实现 COMET 与 FRED 软件的接口，并编写测试用模板和流程模板。

于2015年 8 月份离职。 由于家人生病，在家照顾，同时学习python 和软件开发相关内容。


1) 软件接口的二次开发。
2) 承接光学设计专案。
3) 软件售后的培训课程。
4) 客户问题技术支持，与原厂沟通。接受国外专家的培训。
4) 软件相关书籍翻译（主要英译汉）。

讯技光电（上海）有限公司主要业务是光学仿真软件，包括美国的FRED， Macleod，德国的 VirtualLab 等。
在职期间：
1) 学习新软件并为客户做功能展示讲解(LCDmaster PcModWin5)
2) 承接光学设计仿真专案若干，包括光纤与成像系统仿真等。
3) 搭建并维护内网服务器一部，使用 redhat 与 samba 服务，方便管理公司资料。
4) 翻译国外镀膜设计专著一本（约27万字, 公式排版校对等部分工作有同事和一名实习生帮助）。http://www.infotek.com.cn/html/26/20150810574.html 校正更新书籍一本（FRED光学工程仿真，约500页，增加4章）。 http://infotek.com.cn/html/26/20111013289.html
5) 与合作公司实现 COMET 与 FRED 软件的接口，并编写测试用模板和流程模板。

于2015年 8 月份离职。 由于家人生病，在家照顾，同时学习python 和软件开发相关书籍。


+ 英文流利，翻译过一本光学方面的专著
+ 使用GTD 作为个人管理系统，自我驱动，不断学习。
+ 自学SICP，了解函数式编程和面向对象等思想。
+ 掌握 C 语言，熟练掌握算法和数据结构。
+ 熟练掌握 python。
+ 熟练使用 Git 版本控制工具。
+ 熟悉 MongoDB。
+ 熟悉TCP/IP 协议，Django 网络框架，python 爬虫相关知识。
+ 熟练使用 Linux系统，shell 命令和脚本等。使用Linux 四年。
+ 读过计算机专业书超过50 本，一半为英文原版书。
+ EMACS 爱好者，熟练配置各种开发环境。
+ 个人项目在github 主页，包括搭建个人博客的代码，LISP 实现的数独(sudoku)求解器等。https://github.com/chenjinqian/

+ Skill set.

+ translation works

###  金融类的web平台
